
import { Coin, IndicatorDefinition, TrafficLight } from './types';

// --- BASIC VOCABULARY (Senior-First) ---
export const BASIC_VOCABULARY = [
  { name: "Altcoin", summary: "Any cryptocurrency that is not Bitcoin. Examples include Ethereum, Solana, and Cardano." },
  { name: "Bear Market", summary: "A period when prices are falling and investors are pessimistic (selling). Think of a bear swiping its paws DOWN." },
  { name: "Blockchain", summary: "A digital ledger (record book) that records all transactions. It is secure because it is shared across many computers." },
  { name: "Bull Market", summary: "A period when prices are rising and investors are optimistic (buying). Think of a bull thrusting its horns UP." },
  { name: "DEX (Decentralized Exchange)", summary: "A marketplace where people trade directly with each other without a middleman company (like Revolut or Coinbase)." },
  { name: "Equity", summary: "The actual value of your cash plus your investments right now. If you sell everything, this is what you keep." },
  { name: "Fiat", summary: "Traditional government money like US Dollars ($), Euro (€), or Swiss Francs (CHF)." },
  { name: "FOMO", summary: "'Fear Of Missing Out'. The urge to buy quickly because you see the price rising and don't want to miss the profit. This is risky!" },
  { name: "HODL", summary: "A misspelling of 'Hold' that became famous. It means holding onto your coins for the long term, no matter how much the price moves." },
  { name: "Limit Order", summary: "An order to buy or sell a coin only when it reaches a specific price you choose." },
  { name: "Liquidity", summary: "How easy it is to sell a coin. High liquidity means you can sell instantly. Low liquidity means you might get stuck." },
  { name: "Market Cap", summary: "The total value of a cryptocurrency. Calculated by multiplying the Price by the Total Number of Coins." },
  { name: "Spread", summary: "The difference between the buying price and the selling price. This is often how platforms (like Revolut) make their profit." },
  { name: "Stop Loss", summary: "A safety setting that automatically sells your coin if the price drops to a certain level, limiting your loss." },
  { name: "Volatility", summary: "How fast and how much the price changes. High volatility means the price jumps up and down wildly (High Risk)." },
  { name: "Volume", summary: "The amount of money traded in a coin over a specific time (usually 24 hours). High volume means the trend is strong." },
  { name: "Wallet", summary: "A digital app or physical device where you store the passwords (keys) to access your cryptocurrency." },
  { name: "Whale", summary: "An individual or company that owns a huge amount of cryptocurrency. When they trade, they can move the market price." }
];

// --- PATTERN DEFINITIONS ---
export const PATTERN_DEFINITIONS: Record<string, string> = {
  // Geometric Patterns (Legacy/AI)
  'Double Bottom': 'A bullish reversal pattern describing a drop, a rebound, another drop to the same level, and a second rebound.',
  'Head & Shoulders': 'A bearish reversal pattern characterized by a peak, a higher peak, and then a lower peak.',
  'Bull Flag': 'A continuation pattern where a strong upward move is followed by a slight downward drift before another rise.',
  'Bear Flag': 'A continuation pattern where a strong downward move is followed by a slight upward drift before another drop.',
  'Cup and Handle': 'A bullish continuation pattern resembling a cup with a handle, suggesting an upward trend.',
  'Ascending Triangle': 'A bullish pattern characterized by a flat upper trend line and a rising lower trend line.',
  'Golden Cross': 'A bullish breakout pattern formed when a short-term moving average crosses above a long-term moving average.',
  'Death Cross': 'A bearish pattern formed when a short-term moving average crosses below a long-term moving average.',
  'Falling Wedge': 'A bullish pattern formed by two converging downward trend lines.',
  'Rising Wedge': 'A bearish pattern formed by two converging upward trend lines.',

  // Real Candlestick Patterns (New)
  'Bullish Engulfing': 'A strong reversal signal where a small red candle is followed by a large green candle that completely covers ("engulfs") it.',
  'Bearish Engulfing': 'A top reversal signal where a small green candle is followed by a large red candle that completely covers it.',
  'Dragonfly Doji': 'A potential reversal candle with a long lower wick and no upper wick, showing buyers rejected lower prices.',
  'Gravestone Doji': 'A bearish reversal candle with a long upper wick and no lower wick, showing sellers rejected higher prices.',
  'Hammer': 'A bullish reversal candle formed during a downtrend. It has a small body and a long lower wick.',
  'Shooting Star': 'A bearish reversal candle formed during an uptrend. It has a small body and a long upper wick.',
  'Morning Star': 'A 3-candle bullish reversal pattern: A long red candle, a small gap-down candle, and a long green candle.',
  'Evening Star': 'A 3-candle bearish reversal pattern: A long green candle, a small gap-up candle, and a long red candle.',
  'Doji': 'A candle where the Open and Close prices are virtually equal. It represents indecision in the market.',
  'Marubozu': 'A powerful candle with no wicks. If green, buyers controlled the entire session. If red, sellers dominated.',
  'Three White Soldiers': 'A strong bullish pattern consisting of three consecutive long green candles with higher closes.',
  'Three Black Crows': 'A strong bearish pattern consisting of three consecutive long red candles with lower closes.',

  // Divergences
  'Bullish RSI Divergence': 'Price made a lower low, but RSI made a higher low. This indicates selling momentum is weakening (Potential Buy).',
  'Bearish RSI Divergence': 'Price made a higher high, but RSI made a lower high. This indicates buying momentum is weakening (Potential Sell).'
};

// --- INDICATORS (Complete Revolut List) ---
export const INDICATORS: IndicatorDefinition[] = [
  { name: "52 Week High/Low", summary: "Shows the highest and lowest price over the last year. Key for assessing long-term trend strength; breaking these levels often signals a major breakout or breakdown in market sentiment." },
  { name: "Accelerator Oscillator", summary: "Measures acceleration or deceleration of the current driving force. It serves as an early warning signal for trend changes before they are visible in price action." },
  { name: "Accumulation/Distribution", summary: "Volume-based indicator that tracks the flow of money into or out of an asset. It spots divergences between price and volume, often signaling a potential reversal." },
  { name: "Accumulative Swing Index", summary: "Used to confirm trendline breakouts on charts. It compiles a cumulative total of swing index values to provide a comprehensive view of the long-term trend." },
  { name: "Advance/Decline", summary: "Market breadth indicator showing the difference between the number of advancing and declining assets. It validates market trends." },
  { name: "Arnaud Legoux Moving Average", summary: "A moving average designed to have zero phase lag and high smoothness. It uses Gaussian distribution to filter noise, allowing traders to catch trends early." },
  { name: "Aroon", summary: "Identifies whether a stock is trending and the strength of that trend. It uses two lines (Up and Down) to measure time since the last high or low." },
  { name: "Average Directional Index", summary: "Measures the strength of a trend but not its direction. Readings above 25 indicate a strong trend (up or down)." },
  { name: "Average Price", summary: "A simple average of the High, Low, and Close prices for a period. It provides a smoothed view of the 'true' price action." },
  { name: "Average True Range", summary: "Measures market volatility by decomposing the entire range of an asset price for that period. It does not indicate direction but helps in setting stop-loss levels." },
  { name: "Awesome Oscillator", summary: "A momentum indicator calculating the difference between a 34-period and 5-period Simple Moving Average. It confirms trends and anticipates reversals." },
  { name: "Balance of Power", summary: "Measures the strength of buying and selling pressure. It evaluates the ability of bulls or bears to push price to extreme levels." },
  { name: "Bollinger Bands (20 days)", summary: "A set of three lines: a 20-day simple moving average and two standard deviation bands. It defines the current trading range." },
  { name: "Bollinger Bands %B", summary: "Quantifies where price is relative to the Bollinger Bands. A value above 1 means price is above the upper band, while below 0 implies it is below the lower band." },
  { name: "Bollinger Bands Width", summary: "Measures the distance between the Upper and Lower Bollinger Bands. Narrow width (squeeze) often precedes explosive breakouts." },
  { name: "Chaikin Money Flow", summary: "Measures the amount of Money Flow Volume over a specific period. It combines price and volume to identify buying or selling pressure." },
  { name: "Chaikin Oscillator", summary: "A momentum indicator for the Accumulation/Distribution Line. It calculates the difference between 3-day and 10-day EMAs." },
  { name: "Chaikin Volatility", summary: "Calculates the spread between the high and low prices over a specific period. It identifies volatility expansions and contractions." },
  { name: "Chande Kroll Stop", summary: "A trend-following indicator that calculates stop-loss levels based on the average true range and volatility." },
  { name: "Chande Momentum Oscillator", summary: "A pure momentum oscillator that measures the strength of trends. It uses data from both up and down days directly." },
  { name: "Chop Zone", summary: "Visualizes trendiness versus choppiness using color codes. Turquoise indicates a trending market, while other colors suggest sideways action." },
  { name: "Choppiness Index", summary: "Determines if the market is trending or ranging. Higher values (above 61.8) indicate consolidation, while lower values suggest a strong trend." },
  { name: "Commodity Channel Index", summary: "Identifies cyclical trends and overbought/oversold levels. Originally for commodities, it measures current price level relative to an average." },
  { name: "Connors RSI", summary: "A composite indicator combining 3-period RSI, Up/Down Length, and Rate of Change. Designed specifically for short-term trading." },
  { name: "Coppock Curve", summary: "A long-term momentum indicator used to identify major market bottoms. It calculates a weighted moving average of the rate of change." },
  { name: "Correlation - Log", summary: "Measures the logarithmic correlation between two assets. Useful for analyzing relationships in volatile markets like crypto." },
  { name: "Correlation Coefficient", summary: "Measures the statistical relationship between two assets on a scale of -1 to +1." },
  { name: "Detrended Price Oscillator", summary: "Removes long-term trends from prices to highlight short-term cycles, making it easier to identify overbought/oversold levels." },
  { name: "Directional Movement", summary: "Consists of the Plus Directional Indicator (+DI) and Minus Directional Indicator (-DI). It identifies the direction of the trend." },
  { name: "Donchian Channels", summary: "Three lines generated by moving average calculations that show the highest high and lowest low over a set period. Identifies breakouts." },
  { name: "Double EMA", summary: "Reduces the lag of a traditional EMA. It subtracts a smoothed EMA from a doubled EMA calculation, providing a faster-reacting average." },
  { name: "Ease of Movement", summary: "Relates price change to volume. It shows how easily price can move; high positive values indicate price is advancing with low volume resistance." },
  { name: "Elder's Force Index", summary: "Combines price movement and volume to measure the power behind a move. Positive spikes signal strong buying pressure." },
  { name: "EMA Cross", summary: "A signal generated when a short-term Exponential Moving Average crosses a long-term one. 'Golden Cross' is bullish." },
  { name: "Envelopes", summary: "Plots two moving average envelopes above and below a standard moving average. Defines the upper and lower boundaries of a trading range." },
  { name: "Fisher Transform", summary: "Converts prices into a Gaussian normal distribution. It highlights price reversals by creating sharp turning points." },
  { name: "Guppy Multiple Moving Average", summary: "Uses two groups of moving averages (short-term and long-term) to identify the relationship between short-term traders and long-term investors." },
  { name: "Historical Volatility", summary: "Measures the fluctuations of closing prices over a past period. It assesses the risk associated with an asset." },
  { name: "Hull Moving Average", summary: "A moving average that reduces lag while improving smoothing. It uses weighted averages of half-periods to eliminate lag." },
  { name: "Ichimoku Cloud", summary: "A comprehensive collection of indicators showing support, resistance, trend direction, and momentum. The 'Cloud' represents potential zones." },
  { name: "Keltner Channels", summary: "Volatility-based bands placed above and below an Exponential Moving Average. Unlike Bollinger Bands, they use ATR for width." },
  { name: "Klinger Oscillator", summary: "Volume-based indicator designed to determine long-term trends of money flow while remaining sensitive to short-term fluctuations." },
  { name: "Know Sure Thing", summary: "A momentum oscillator based on four different timeframes of smoothed Rate of Change." },
  { name: "Least Squares Moving Average", summary: "Uses linear regression to calculate the 'best fit' line for a specific period. Acts as a moving trendline." },
  { name: "Linear Regression Curve", summary: "Plots the end points of linear regression lines for each day. It smooths price data using a statistical fit." },
  { name: "Linear Regression Slope", summary: "Measures the slope (angle) of the linear regression line. It determines the strength and direction of the trend." },
  { name: "MA Cross", summary: "A general strategy involving two Moving Averages (fast and slow). It signals buy/sell opportunities when lines cross." },
  { name: "MA with EMA Cross", summary: "Combines a Simple Moving Average with an Exponential Moving Average to balance trend confirmation with responsiveness." },
  { name: "MACD", summary: "A trend-following momentum indicator showing the relationship between two moving averages of price." },
  { name: "Majority Rule", summary: "Tracks the percentage of days with rising prices over a set period. It confirms trend strength." },
  { name: "Mass Index", summary: "Identifies trend reversals by measuring the narrowing and widening of the trading range." },
  { name: "McGinley Dynamic", summary: "A moving average that adjusts itself to market speed. It minimizes lag and avoids whipsaws." },
  { name: "Median Price", summary: "The midpoint of the day's high and low prices. It provides a simple view of the day's 'average' value." },
  { name: "Momentum", summary: "Measures the rate of change of price movement. It compares the current price to a past price." },
  { name: "Money Flow Index", summary: "A volume-weighted RSI. It measures buying and selling pressure by using both price and volume." },
  { name: "Moving Average", summary: "The core indicator smoothing price data to form a trend-following line." },
  { name: "Moving Average Adaptive", summary: "Adapts its sensitivity to market volatility. In trending markets, it follows price closely; in choppy markets, it smooths out noise." },
  { name: "Moving Average Channel", summary: "A band created by shifting a moving average up and down by a set percentage." },
  { name: "Moving Average Double", summary: "Using two moving averages (e.g., a fast and a slow one) on the same chart." },
  { name: "Moving Average Exponential", summary: "Weights recent price data more heavily than older data. It reacts faster to recent price changes than a Simple MA." },
  { name: "Moving Average Hamming", summary: "Applies a Hamming window function to weight price data. This signal processing technique reduces edge noise and lag." },
  { name: "Moving Average Multiple", summary: "Using a cluster of moving averages (e.g., 6 or 12 lines) simultaneously." },
  { name: "Moving Average Simple (100 days)", summary: "A medium-to-long-term trend indicator. Price holding above it suggests a sustained bullish phase." },
  { name: "Moving Average Simple (20 days)", summary: "A short-term trend indicator. It tracks the average price of the last trading month." },
  { name: "Moving Average Simple (200 days)", summary: "The gold standard for long-term market trends. Institutions watch this level closely." },
  { name: "Moving Average Simple (50 days)", summary: "A key medium-term trend indicator. Crossovers with the 200-day MA (Golden/Death Cross) are major signals." },
  { name: "Moving Average Simple (9 days)", summary: "A very short-term trend indicator. Often used as a 'signal line' or for fast-moving assets." },
  { name: "Moving Average Triple", summary: "Uses three moving averages (Short, Medium, Long) to filter signals." },
  { name: "Moving Average Weighted", summary: "Assigns linearly decreasing importance to older data." },
  { name: "Net Volume", summary: "Calculates the difference between up-volume (buying) and down-volume (selling) over a period." },
  { name: "On Balance Volume", summary: "Adds volume on up days and subtracts volume on down days. It measures buying pressure." },
  { name: "Parabolic SAR", summary: "A trend-following indicator that places dots above or below price candles. Highlights trend direction and stop-loss levels." },
  { name: "Pivot Points Standard", summary: "Horizontal support and resistance levels calculated from the previous day's High, Low, and Close." },
  { name: "Price Channel", summary: "Lines plotting the highest high and lowest low over a set period. It defines the current trading range." },
  { name: "Price Oscillator", summary: "A momentum indicator calculated by subtracting a longer moving average from a shorter one." },
  { name: "Price Volume Trend", summary: "Similar to OBV but adjusts based on the percentage price change." },
  { name: "Rank Correlation Index", summary: "Measures the correlation between price rank and time rank." },
  { name: "Rate Of Change", summary: "Measures the percentage change in price between the current price and a price a certain number of periods ago." },
  { name: "Ratio", summary: "Compares the price of one asset to another (e.g., ETH/BTC). It shows relative strength." },
  { name: "Relative Strength Index", summary: "A momentum oscillator ranging from 0 to 100. It identifies overbought (>70) and oversold (<30) conditions." },
  { name: "Relative Vigor Index", summary: "Compares the closing price to the trading range. It assumes prices close higher in uptrends and lower in downtrends." },
  { name: "Relative Volatility Index", summary: "Measures the direction of volatility. Similar to RSI but uses standard deviation of price changes." },
  { name: "RSI - Relative Strength Index (14 days)", summary: "The standard setting for RSI. It looks back 14 periods to gauge momentum." },
  { name: "SMI Ergodic Indicator/Oscillator", summary: "A double-smoothed momentum oscillator based on the True Strength Index." },
  { name: "Smoothed Moving Average", summary: "An extensive smoothing moving average that removes short-term fluctuations entirely." },
  { name: "Spread", summary: "The difference between the Bid and Ask price, or between two related assets." },
  { name: "Standard Deviation", summary: "Measures the dispersion of prices from their mean. High values indicate high volatility." },
  { name: "Standard Error", summary: "Measures how far current prices deviate from the linear regression line. It indicates trend reliability." },
  { name: "Standard Error Bands", summary: "Plots bands above and below a Linear Regression line using Standard Error." },
  { name: "Stochastic", summary: "Compares a closing price to its price range over a period. Values >80 are overbought, <20 are oversold." },
  { name: "Stochastic RSI", summary: "Applies the Stochastic formula to RSI values, not price. It increases sensitivity." },
  { name: "Super Trend", summary: "A trend-following overlay that changes color based on trend direction. Uses ATR to set stop-loss levels." },
  { name: "Trend Strength Index", summary: "Measures the strength of a trend without a fixed boundary." },
  { name: "Triple EMA", summary: "A moving average that undergoes three smoothing passes to eliminate lag." },
  { name: "TRIX", summary: "A momentum oscillator showing the percent rate of change of a triple exponentially smoothed moving average." },
  { name: "True Strength Index", summary: "A momentum oscillator that double-smooths price changes. It spots overbought/oversold conditions with less noise." },
  { name: "Typical Price", summary: "The average of the High, Low, and Close prices for a single period." },
  { name: "Ultimate Oscillator", summary: "Combines momentum across three different timeframes (short, medium, long)." },
  { name: "Volatility Close-to-Close", summary: "Measures volatility using only closing prices. Provides a simplified view of market risk." },
  { name: "Volatility Index", summary: "A measure of market expectations of near-term volatility (like the VIX). Often called the 'fear gauge'." },
  { name: "Volatility O-H-L-C", summary: "Measures volatility using Open, High, Low, and Close prices." },
  { name: "Volatility Zero Trend Close-to-Close", summary: "Estimates volatility assuming zero trend drift. Focuses on the random component of price changes." },
  { name: "Volume", summary: "The total amount of an asset traded in a specific period. It is the fuel of the market." },
  { name: "Volume Oscillator", summary: "Displays the difference between two moving averages of volume." },
  { name: "Volume Profile Fixed Range", summary: "Shows volume traded at specific price levels over a selected time range." },
  { name: "Volume Profile Visible Range", summary: "Automatically displays volume-by-price for the visible candles on the screen." },
  { name: "Vortex Indicator", summary: "Uses two oscillating lines (VI+ and VI-) to identify trend reversals. Modeled after water flow vortices." },
  { name: "VWAP", summary: "Volume Weighted Average Price. It calculates the average price an asset has traded at throughout the day." },
  { name: "VWMA", summary: "Volume Weighted Moving Average. A moving average that gives more weight to periods with high volume." },
  { name: "Williams %R", summary: "A momentum indicator inversely related to the Stochastic Oscillator. Ranges from 0 to -100." },
  { name: "Williams Alligator", summary: "Uses three smoothed moving averages (Jaw, Teeth, Lips) to determine trend." },
  { name: "Williams Fractal", summary: "Identifies recurring geometric patterns on price charts. Marks local highs and lows." },
  { name: "Zig Zag", summary: "Filters out price changes smaller than a specific percentage to reveal underlying structure." }
];

// Helper to generate mock data for the 300+ coins without hitting an API
const generateMockData = (symbol: string, name: string, category: string): Coin => {
  let hash = 0;
  for (let i = 0; i < symbol.length; i++) {
    hash = symbol.charCodeAt(i) + ((hash << 5) - hash);
  }
  
  const priceTier = Math.abs(hash % 4); 
  let price = 0;
  if (["BTC", "YFI", "PAXG", "MKR", "ETH"].includes(symbol)) {
    price = 2000 + (Math.abs(hash) % 60000); 
  } else if (priceTier === 0) price = 0.05 + (Math.abs(hash) % 1); 
  else if (priceTier === 1) price = 1 + (Math.abs(hash) % 10);    
  else if (priceTier === 2) price = 10 + (Math.abs(hash) % 90);   
  else price = 100 + (Math.abs(hash) % 400);                      

  const volatility = Math.abs(hash) % 10 > 7 ? TrafficLight.RED : (Math.abs(hash) % 10 > 4 ? TrafficLight.YELLOW : TrafficLight.GREEN);
  const change24h = (Math.abs(hash) % 200 - 100) / 10; 

  const website = `https://${name.toLowerCase().replace(/\s/g, '')}.org`;
  const whitepaper = `https://${name.toLowerCase().replace(/\s/g, '')}.org/whitepaper.pdf`;
  
  // High quality repository from SpotHQ containing over 500+ coins. 
  // This is much more comprehensive than CoinCap for the full list of 300+ coins.
  const image = `https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/128/color/${symbol.toLowerCase()}.png`;

  return { symbol, name, category, price, change24h, volatility, website, whitepaper, image };
};

const RAW_COIN_LIST = [
    ["1INCH", "1Inch Network", "DEX"],
    ["A8", "Ancient8", "Gaming / VR"],
    ["AAVE", "Aave", "Lending / borrowing"],
    ["ABT", "Arcblock", "App development"],
    ["ACH", "Alchemy Pay", "Payments"],
    ["ACS", "Access Protocol", "NFT / Social"],
    ["ACX", "Across Protocol", "Layer 2 / Sidechain"],
    ["ADA", "Cardano", "Layer 1"],
    ["AERGO", "Aergo", "Layer 1"],
    ["AERO", "Aerodome Finance", "DEX"],
    ["AGLD", "Adventure Gold", "Gaming / VR"],
    ["AIOZ", "AIOZ Network", "Data management and storage"],
    ["AKT", "Akash Network", "IoT / Shared compute"],
    ["ALCX", "Alchemix", "Lending / borrowing"],
    ["ALEO", "Aleo", "Layer 1"],
    ["ALEPH", "Aleph Cloud", "IoT / Shared compute"],
    ["ALGO", "Algorand", "Layer 1"],
    ["ALICE", "My NeighborAlice", "Gaming / VR"],
    ["AMP", "Amp", "Payments"],
    ["ANKR", "Ankr", "IoT / Shared compute"],
    ["APE", "ApeCoin", "NFT / Social"],
    ["API3", "API3", "App development"],
    ["APT", "Aptos", "Layer 1"],
    ["ARB", "Arbitrum", "Layer 2 / Sidechain"],
    ["ARKM", "Arkham", "Data management and storage"],
    ["ARPA", "ARPA", "Data management and storage"],
    ["ASM", "Assemble AI", "IoT / Shared compute"],
    ["AST", "AirSwap", "DEX"],
    ["ATH", "Aethir", "IoT / Shared compute"],
    ["ATOM", "Cosmos", "Layer 1"],
    ["AUCTION", "Bounce Token", "App development"],
    ["AUDIO", "Audius", "NFT / Social"],
    ["AURORA", "Aurora", "Layer 2 / Sidechain"],
    ["AVAX", "Avalanche", "Layer 1"],
    ["AVT", "Aventus", "Layer 1"],
    ["AXS", "Axie Infinity", "Gaming / VR"],
    ["BADGER", "Badger DAO", "Asset management"],
    ["BAL", "Balancer", "DEX"],
    ["BAND", "Band Protocol", "Data management and storage"],
    ["BAT", "Basic Attention Token", "NFT / Social"],
    ["BCH", "Bitcoin Cash", "Currencies"],
    ["BENJI", "Basenji", "Memes"],
    ["BERA", "Berachain", "Layer 1"],
    ["BICO", "Biconomy", "App development"],
    ["BIGTIME", "Big Time", "Gaming / VR"],
    ["BLUR", "Blur", "NFT / Social"],
    ["BLZ", "Bluzelle", "Data management and storage"],
    ["BNB", "BNB", "Layer 1"],
    ["BNT", "Bancor", "DEX"],
    ["BOBA", "Boba Network", "Layer 2 / Sidechain"],
    ["BONK", "Bonk", "Memes"],
    ["BTC", "Bitcoin", "Currencies"],
    ["BTRST", "Braintrust", "App development"],
    ["C98", "Coin 98", "App development"],
    ["CAT", "Simon's Cat", "Memes"],
    ["CELO", "Celo", "Payments"],
    ["CELR", "Celer Network", "Layer 2 / Sidechain"],
    ["CHILLGUY", "Just a chill guy", "Memes"],
    ["CHZ", "Chiliz", "NFT / Social"],
    ["CLV", "CLV", "Layer 1"],
    ["COMP", "Compound", "Lending / borrowing"],
    ["COOKIE", "Cookie DAO", "App development"],
    ["COTI", "COTI", "Payments"],
    ["COW", "CoW Protocol", "DEX"],
    ["CRO", "Cronos", "Layer 1"],
    ["CRV", "Curve DAO Token", "DEX"],
    ["CTC", "Creditcoin", "Lending / borrowing"],
    ["CTSI", "Cartesi", "Layer 2 / Sidechain"],
    ["CVC", "Civic", "App development"],
    ["CVX", "Convex Finance", "Asset management"],
    ["CXT", "Covalent X Token", "Data management and storage"],
    ["DASH", "DASH", "Currencies"],
    ["DEGEN", "Degen", "Memes"],
    ["DIA", "DIA", "Data management and storage"],
    ["DIMO", "DIMO", "IoT / Shared compute"],
    ["DOGE", "DodgeCoin", "Memes"],
    ["DOGINME", "doginme", "Memes"],
    ["DOT", "Polkadot", "Layer 1"],
    ["DRIFT", "Drift", "DEX"],
    ["DYDX", "dYdX", "DEX"],
    ["EDGE", "Definitive", "App development"],
    ["EGLD", "MultiversX", "Layer 1"],
    ["EIGEN", "EigenLayer", "App development"],
    ["ELA", "Elastos", "Layer 1"],
    ["ENA", "Ethena", "Asset backed"],
    ["ENS", "Etherum Name Service", "Data management and storage"],
    ["EOS", "EOS", "Layer 1"],
    ["ETC", "Etherum Classic", "Layer 1"],
    ["ETH", "Ether", "Layer 1"],
    ["FAI", "Freysa", "Gaming / VR"],
    ["FARM", "Harvest Finance", "Asset management"],
    ["FET", "Fetch.ai", "IoT / Shared compute"],
    ["FIDA", "Solana Name Service", "Data management and storage"],
    ["FIL", "Filecoin", "Data management and storage"],
    ["FIS", "StaFi", "Asset management"],
    ["FLOKI", "FLOKI", "Memes"],
    ["FLOW", "Flow", "Layer 1"],
    ["FLR", "Flare", "Layer 1"],
    ["FORT", "Forta", "App development"],
    ["FORTH", "Ampleforth Governance Token", "Currencies"],
    ["FWOG", "FWOG", "Memes"],
    ["FX", "Function X", "Layer 1"],
    ["GALA", "Gala", "Gaming / VR"],
    ["GFI", "Goldfinch", "Asset backed"],
    ["GHST", "Aavegotchi", "Gaming / VR"],
    ["GIGA", "Gigachad", "Memes"],
    ["GLM", "Golem Network", "IoT / Shared compute"],
    ["GMT", "GMT", "Gaming / VR"],
    ["GODS", "Gods Unchained", "Gaming / VR"],
    ["GRASS", "Grass", "IoT / Shared compute"],
    ["GRT", "The Graph", "Data management and storage"],
    ["GST", "Green Satoshi Token", "Gaming / VR"],
    ["GTC", "Gitcoin", "App development"],
    ["HBAR", "Hedera", "Layer 1"],
    ["HFT", "Hashflow", "DEX"],
    ["HIGH", "Highstreet", "Gaming / VR"],
    ["HNT", "Helium", "IoT / Shared compute"],
    ["HONEY", "Hivemapper", "IoT / Shared compute"],
    ["HOPR", "HOPR", "Data management and storage"],
    ["ICP", "Internet Computer", "Layer 1"],
    ["IDEX", "Idex", "DEX"],
    ["ILV", "Illuvium", "Gaming / VR"],
    ["IMX", "Immutable", "Gaming / VR"],
    ["INJ", "Injective", "Layer 1"],
    ["IO", "io.net", "IoT / Shared compute"],
    ["IOTX", "IoTeX", "IoT / Shared compute"],
    ["IP", "Story", "NFT / Social"],
    ["JASMY", "JasmyCoin", "IoT / Shared compute"],
    ["JTO", "Jito", "Asset management"],
    ["JUP", "Jupiter", "DEX"],
    ["KAITO", "Kaito", "App development"],
    ["KARRAT", "KARRAT", "Gaming / VR"],
    ["KAVA", "Kava", "Layer 1"],
    ["KNC", "Kyber Network Crystal v2", "DEX"],
    ["KRL", "Kryll", "Asset management"],
    ["KSM", "Kusama", "Layer 1"],
    ["L3", "Layer3", "App development"],
    ["LCX", "LCX", "DEX"],
    ["LDO", "Lido", "Asset management"],
    ["LINK", "Chainlink", "Data management and storage"],
    ["LMWR", "LimeWire", "NFT / Social"],
    ["LOKA", "League of Kingdoms Arena", "Gaming / VR"],
    ["LPT", "Livepeer", "IoT / Shared compute"],
    ["LQTY", "Liquity", "Lending / borrowing"],
    ["LRC", "Loopring", "Layer 2 / Sidechain"],
    ["LRDS", "BLOCKLORDS", "Gaming / VR"],
    ["LTC", "Litecoin", "Currencies"],
    ["MAGIC", "Treasure", "Gaming / VR"],
    ["MANA", "Decentraland", "Gaming / VR"],
    ["MASK", "Mask Network", "NFT / Social"],
    ["MATH", "MATH", "App development"],
    ["MATIC", "Polygon", "Layer 2 / Sidechain"],
    ["MDT", "Measurable Data Token", "Data management and storage"],
    ["ME", "Magic Eden", "NFT / Social"],
    ["MELANIA", "Official Melania Meme", "Memes"],
    ["METIS", "Metis", "Layer 2 / Sidechain"],
    ["MEW", "cat in a dogs world", "Memes"],
    ["MIGGLES", "Mr Miggles", "Memes"],
    ["MINA", "Mina", "Layer 1"],
    ["MKR", "Maker", "Asset management"],
    ["MLN", "Enzyme", "Asset management"],
    ["MNDE", "Marinade", "Asset management"],
    ["MOG", "Mog Coin", "Memes"],
    ["MOODENG", "Moodeng", "Memes"],
    ["MORPHO", "Morpho", "Lending / borrowing"],
    ["MSOL", "Marinade Staked SOL", "Asset management"],
    ["MUSE", "Muse", "NFT / Social"],
    ["NCT", "PolySwarm", "App development"],
    ["NEAR", "NEAR Protocol", "Layer 1"],
    ["NEIRO", "First Neiro On Etherum", "Memes"],
    ["NEON", "Neon EVM", "Layer 2 / Sidechain"],
    ["NKN", "NK (New Kind of Network)", "IoT / Shared compute"],
    ["NMR", "Numeraire", "IoT / Shared compute"],
    ["OCEAN", "Ocean Protocol", "Data management and storage"],
    ["OGN", "Origin Protocol", "NFT / Social"],
    ["OMNI", "Omni Network", "Layer 1"],
    ["ONDO", "Ondo", "Asset backed"],
    ["OP", "Optimism", "Layer 2 / Sidechain"],
    ["ORCA", "Orca", "DEX"],
    ["OSMO", "Osmosis", "DEX"],
    ["OXT", "Orchid", "Data management and storage"],
    ["PARTI", "Particle Network", "App development"],
    ["PENGU", "Pudgy Penguins", "Memes"],
    ["PEPE", "Pepe", "Memes"],
    ["PERP", "Perpetual Protocol", "DEX"],
    ["PIRATE", "Pirate Nation", "Gaming / VR"],
    ["PLA", "PlayDapp", "Gaming / VR"],
    ["PNG", "pangolin", "DEX"],
    ["PNUT", "Peanut the Squirrel", "Memes"],
    ["POL", "POL (ex-MATIC)", "Layer 2 / Sidechain"],
    ["POLS", "Polkastarter", "App development"],
    ["POND", "Marlin", "Layer 2 / Sidechain"],
    ["PONKE", "PONKE", "Memes"],
    ["POPCAT", "Popcat", "Memes"],
    ["POWR", "Powerledger", "IoT / Shared compute"],
    ["PRCL", "Parcl", "Asset backed"],
    ["PRIME", "Echelon Prime", "Gaming / VR"],
    ["PRO", "Propy", "App development"],
    ["PROMPT", "Wayfinder", "IoT / Shared compute"],
    ["PUMP", "Pump Fun", "Memes"],
    ["PUNDIX", "Pundi X", "Payments"],
    ["PYR", "Vulcan Forged", "Gaming / VR"],
    ["PYTH", "Pyth Network", "Data management and storage"],
    ["QI", "BENQI", "Lending / borrowing"],
    ["QNT", "Quant", "App development"],
    ["RAD", "Radicle", "App development"],
    ["RARE", "SuperRare", "NFT / Social"],
    ["RARI", "RARI", "NFT / Social"],
    ["RED", "RedStone", "Data management and storage"],
    ["RENDER", "Render", "IoT / Shared compute"],
    ["REQ", "Request", "Payments"],
    ["REZ", "Renzo", "Asset management"],
    ["RIZE", "RIZE", "Asset backed"],
    ["RLC", "iExec", "IoT / Shared compute"],
    ["ROSE", "Oasis Network", "Layer 1"],
    ["RPL", "Rocket Pool", "Asset management"],
    ["RSR", "Reserve Rights", "Lending / borrowing"],
    ["SAFE", "Safe", "Asset management"],
    ["SAND", "The Sandbox", "Gaming / VR"],
    ["SD", "Stader", "Asset management"],
    ["SEAM", "Seamless", "Lending / borrowing"],
    ["SEI", "SEI", "Layer 1"],
    ["SHDW", "Shadow Token", "Data management and storage"],
    ["SHIB", "Shiba Inu", "Memes"],
    ["SHPING", "shping", "App development"],
    ["SKL", "SKALE", "Layer 2 / Sidechain"],
    ["SNX", "Synthetix", "DEX"],
    ["SOL", "Solana", "Layer 1"],
    ["SPA", "Sperax", "DEX"],
    ["SPELL", "Spell Token", "Lending / borrowing"],
    ["SPX", "SPX6900", "Memes"],
    ["STG", "Stargate Finance", "Layer 2 / Sidechain"],
    ["STORJ", "Storj", "Data management and storage"],
    ["STRK", "Starknet", "Layer 2 / Sidechain"],
    ["STX", "Stacks", "Layer 2 / Sidechain"],
    ["SUI", "Sui", "Layer 1"],
    ["SUKU", "Suku", "App development"],
    ["SUPER", "SuperVerse", "Gaming / VR"],
    ["SUSHI", "SushiSwap", "DEX"],
    ["SWELL", "Swell Network", "Asset management"],
    ["SWIFTC", "SwiftCoin", "Payments"],
    ["SXT", "Space and Time", "Data management and storage"],
    ["T", "Threshold", "App development"],
    ["TAI", "TARS AI", "IoT / Shared compute"],
    ["TAIKO", "Taiko", "Layer 2 / Sidechain"],
    ["TIA", "Celestia", "Layer 1"],
    ["TNSR", "Tensor", "NFT / Social"],
    ["TOKEN", "TokenFi", "Asset management"],
    ["TON", "Toncoin", "Layer 1"],
    ["TOSHI", "Toshi", "Memes"],
    ["TRAC", "OriginTrail", "Data management and storage"],
    ["TRB", "Tellor", "Data management and storage"],
    ["TRU", "TrueFi", "Lending / borrowing"],
    ["TRUMP", "OFFICIAL TRUMP", "Memes"],
    ["TRX", "Tron", "Layer 1"],
    ["TURBO", "Turbo", "Memes"],
    ["UMA", "UMA", "Data management and storage"],
    ["UNI", "Uniswap", "DEX"],
    ["USDC", "USDC", "Payments"],
    ["USDT", "Tether", "Payments"],
    ["VELO", "Velodrome Finance", "DEX"],
    ["VET", "VeChain", "Layer 1"],
    ["VINU", "Vita Inu", "Memes"],
    ["VOXEL", "Voxies", "Gaming / VR"],
    ["VTHO", "VeThor Token", "Layer 1"],
    ["VVV", "Venice Token", "IoT / Shared compute"],
    ["W", "Wormhole", "Layer 2 / Sidechain"],
    ["WAXL", "Wrapped Axelar", "Layer 2 / Sidechain"],
    ["WEN", "Wen", "Memes"],
    ["WIF", "dogwifhat", "Memes"],
    ["WLD", "Worldcoin", "App development"],
    ["WOO", "Woo", "DEX"],
    ["X", "X Empire", "Gaming / VR"],
    ["XCN", "Onyxcoin", "App development"],
    ["XLM", "Stellar", "Layer 1"],
    ["XRP", "XRP", "Currencies"],
    ["XTZ", "Tezos", "Layer 1"],
    ["XYO", "Xyo", "IoT / Shared compute"],
    ["YFI", "Yearn.finance", "Asset management"],
    ["ZEN", "Horizon", "Layer 1"],
    ["ZKJ", "Polyhedra Network", "Layer 2 / Sidechain"],
    ["ZRO", "LayerZero", "Layer 2 / Sidechain"],
    ["ZRX", "0x Protocol", "DEX"]
];

export const COIN_DATA_SEED: Coin[] = RAW_COIN_LIST.map(c => generateMockData(c[0], c[1], c[2]));
